GET http://localhost:1234/api
###
GET http://localhost:1234
### METODO PARA CREAR LAS TABLAS
GET http://localhost:1234/api/initializeSeed
###
### METODO PARA LLAMAR A TODOS LOS AVISTAMIENTOS
GET http://localhost:1234/api/getAllPosts
### METODO PARA CREAR UN USUARIO
POST http://localhost:1234/api/create
Content-Type: application/json

{   
    "sql": "delete * from usuarios",
    "nombre": "Pablo Ore Campos",
    "lastName": "Perez",
    "email": "un email",
    "correo": "correo@gmail.edu",
    "titulo_biologico": "0x123456789ABCDE10153456789ABCDEF",
    "contraseña": "qwerty1234"
}

### METODO PARA POSTEAR UN AVISTAMIENTO
GET http://localhost:1234/api/post

### Metodo para actualizar una tabla de la base de datos
GET http://localhost:1234/api/updateTables
